(defun show-dots (lst)
  (cond ((atom lst)
         (format t "~a" lst))
        (t
           (format t "(")
           (show-dots (car lst))
           (format t " . ")
           (show-dots (cdr lst))
           (format t ")"))))

(defun show-list (lst)
  (cond ((atom lst) (format t "~a" lst))
        (t (format t "[")
           (show-list (car lst))
           (do ((ll (cdr lst) (cdr ll)))
               ((atom ll)
                (unless (null ll)
                  (format t " . ~a" ll))
                (format t "]"))
             (format t " ")
             (show-list (car ll))))))

(show-list '(a b c . d))
(show-list '(a b c))
(show-list '(((a b) c) d))
(show-list '(a (b c)))
(show-list '(a . b))
(show-list 'a)
(show-list nil)
(show-list '(nil))
